# Generated by Django 5.2 on 2025-10-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\sablo\\Dropbox\\mydocs\\business\\islan.dev\\marketing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.ad'),
        ),
    ]
