# Generated by Django 5.2 on 2025-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_url', models.URLField()),
                ('group_set', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
            ],
        ),
    ]
