# Generated by Django 5.2 on 2025-10-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('posts', '0002_alter_ad_image_alter_post_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='engagement.contact'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='message_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
