# Generated by Django 5.2 on 2025-10-17 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_engagement_post_alter_engagement_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
